version: '3.9'
services:
  shopware:
    image: dockware/play:latest
    container_name: shopware.test
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../composer.json:/var/www/html/custom/plugins/MappIntelligence/composer.json
      - ../src:/var/www/html/custom/plugins/MappIntelligence/src
      - "shopware_intelligence_db_volume:/var/lib/mysql"
      - "shopware_intelligence_shop_volume:/var/www/html"
    networks:
      - mapp
  cypress:
    container_name: mapp_e2e_shopware_cypress
    entrypoint: ["/bin/bash", "/cypress_entrypoint.sh"]
    build:
      context: .
      dockerfile: ./Dockerfile.cypress
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js
      - ./cypress_entrypoint.sh:/cypress_entrypoint.sh
      - ./results:/results
      - ./wait-for-it.sh:/wait-for-it.sh
    networks:
      - mapp
volumes:
  shopware_intelligence_db_volume:
    driver: local
  shopware_intelligence_shop_volume:
    driver: local

networks:
    mapp:
      name: mapp_e2e_shopware