.PHONY: set-dev
set-dev:
	ls ./../../../../dev-ops/docker/containers/app/
	$(info ----------------  INFO  ----------------------)
	$(info php docker container set to dev - slow but xdebug)
	$(info ----------------  OUTPUT  ----------------------)
